# Generated by Django 4.0 on 2022-03-25 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 15, 5, 12, 372703, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='country',
            field=models.CharField(default='Россия', max_length=128, verbose_name='страна'),
        ),
    ]
