# Generated by Django 4.0 on 2022-03-26 19:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_shopuser_activation_key_expires_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuserprofile',
            name='age',
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 19, 17, 8, 854367, tzinfo=utc)),
        ),
    ]
