# Generated by Django 4.0 on 2022-03-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_remove_shopuserprofile_age_and_more'),

    ]

    operations = [
    ]
