# Generated by Django 4.0 on 2022-03-27 09:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_merge_20220327_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='age',
            field=models.PositiveIntegerField(default=18, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 9, 56, 57, 868912, tzinfo=utc)),
        ),
    ]
