# Generated by Django 4.0 on 2022-03-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_shopuserprofile_other_social_media_and_more'),
        ('authapp', '0010_alter_shopuser_activation_key_expires'),
    ]

    operations = [
    ]
