# Generated by Django 4.0 on 2022-03-27 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_merge_20220327_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='other_social_media',
            field=models.CharField(blank=True, max_length=128, verbose_name='социальные сети'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 10, 16, 18, 584128, tzinfo=utc)),
        ),
    ]
