# Generated by Django 4.0 on 2022-03-27 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_shopuserprofile_other_social_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 11, 22, 13, 861489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='country',
            field=models.CharField(max_length=128, verbose_name='страна'),
        ),
    ]
