# Generated by Django 4.0 on 2022-03-27 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_alter_shopuser_activation_key_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=256, verbose_name='языки'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 12, 27, 26, 75307, tzinfo=utc)),
        ),
    ]
