# Generated by Django 4.0 on 2022-04-01 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_shopuserprofile_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 16, 36, 33, 710738, tzinfo=utc)),
        ),
    ]
