# Generated by Django 3.2.2 on 2022-05-02 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, unique=True, verbose_name='имя')),
                ('description', models.TextField(blank=True, max_length=128, verbose_name='описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активна')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='имя')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('short_description', models.CharField(max_length=64, verbose_name='короткое описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('price_with_discount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена со скидкой')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество на складе')),
                ('image', models.ImageField(blank=True, upload_to='products_images')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активна')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.productcategory')),
            ],
        ),
    ]
